sudo: required
services:
  - docker

before_install:
  - docker build -t 190111212/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run 190111212/react-test npm test -- --coverage

after_success:
  - docker build -t 190111212/multi-client ./client
  - docker build -t 190111212/multi-nginx ./nginx
  - docker build -t 190111212/multi-server ./server
  - docker build -t 190111212/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push 190111212/multi-client
  - docker push 190111212/multi-nginx
  - docker push 190111212/multi-server
  - docker push 190111212/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env-1
  bucket_name: elasticbeanstalk-us-east-1-102612369513
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY